services:

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama  # persistent models
    ports:
      - "11434:11434"  # Ollama API port
    entrypoint: >
      sh -c "ollama pull gemma:2b && ollama serve"

  orchestrator:
    build: .
    container_name: orchestrator
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434  # internal docker hostname!
    ports:
      - "8000:8000"  # FastAPI port
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
